server:
  port: 3002

spring:
  application:
    name: order-api

hello-api:
  base-url: http://localhost:3001

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      transport: http
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
        aggregation-temporality: cumulative
    logging:
      export:
        endpoint: http://localhost:4318/v1/logs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
